model: yolov8n.pt
data: data/coco6/data.yaml
epochs: 10
imgsz: 640
batch: 8
device: 0
project: runs/augment
name: aug_task_20e
optimizer: auto
seed: 0
deterministic: true

mosaic: 0.8
fliplr: 0.5
hsv_h: 0.015
hsv_s: 0.5
hsv_v: 0.3
translate: 0.05
scale: 0.3
degrees: 5.0
shear: 1.0
perspective: 0.0
mixup: 0.0
copy_paste: 0.0
auto_augment: randaugment
erasing: 0.15

close_mosaic: 10
